### ISSUE TITLE
.NET/Semver version strings support

### ISSUE THREAD

**Issue by lcorneliussen** [migrating-ravens/RavenMigrations#16]
What about supporting "normal" versions like `1.2.5`?

Internally the version could (quite) easily be converted into a long.

**Comment by dportzline83** [comment]
We have a pull request that has a new version scheme proposal: #25. Feel free to discuss this there.

**Comment by dportzline83** [comment]
I've converted this project to use SemVer for it's nuget package versions. But, I'm curious what benefit you see from applying SemVer to internal database versioning?
