### ISSUE TITLE
Migration classes that begin with an underscore or contain multiple adjacent underscores get re-migrated

### ISSUE THREAD

**Issue by rogersillito** [migrating-ravens/RavenMigrations#20]
When this happens the migration runner doesn't pick these up as already applied in the list of MigrationDocuments.  As a result the problem migration keeps getting re-applied.  I fixed this in my fork - https://github.com/khalidabuhakmeh/RavenMigrations/pull/19# (https://github.com/rogersillito/RavenMigrations/commit/1a84e258370997703bc7ee0a9b977e552a152af9)

**Comment by dportzline83** [comment]
Resolved by #19 / #35
