### ISSUE TITLE
Allow custom migration version numbering

### ISSUE THREAD

**Issue by absynce** [migrating-ravens/RavenMigrations#37]
Similar to [FluentMigrator](https://github.com/schambers/fluentmigrator/wiki/Enforce-migration-version-numbering-rules), `MigrationAttribute` could optionally be inherited using a custom attribute.

This would create a generic solution for @brunomlopes' alternative version scheme in #25.

**Comment by dportzline83** [comment]
Not a bad idea. I'm not following this project much anymore as I've been moved onto something else at work now. I'm happy to make anyone a collaborator/owner that wants to continue moving this forward.

**Comment by absynce** [comment]
@dportzline83 thanks for the quick response! I think the change is rather simple to allow. I've created a fork and trying my changes now. If it works I'll create a PR. 

If you'd rather me take over as a collab/owner, I'm willing to help. I'm in a similar situation in that most of my time spent on this is at work. So if my priorities are shifted, I wouldn't be able to spend as much time on it.
