### ISSUE TITLE
Move to 4.0?

### ISSUE THREAD

**Issue by JudahGabriel** [migrating-ravens/RavenMigrations#43]
Hi @dportzline83 

RavenMigrations is currently on Raven 2.5, which is quite outdated. Would you accept a PR that upgrades to the latest Raven 4.x?

**Comment by JudahGabriel** [comment]
Also, could I migrate the code to .NET Core? Would you accept a PR for that?

**Comment by dportzline83** [comment]
I have no issues with those ideas. I'm not using Raven anymore, so I don't
have much of a stake in it. I'd be curious if others who are watching this
thread have opinions.

**Comment by JudahGabriel** [comment]
Thanks!

If you think you won't be maintaining this repository any longer, I'd be willing to take over ownership. (I can still keep your name as an author in the NuGet package if you like.)

**Comment by dportzline83** [comment]
Yeah, I'm happy to have someone else take over. I'm on vacation today, but
I'll try to get back with you later this week. Remind me if I forget :)

**Comment by JudahGabriel** [comment]
Sounds good. Enjoy your vacation.

**Comment by dportzline83** [comment]
@JudahGabriel I've added you as a collaborator on the repository. Looks like @khalidabuhakmeh already added you to the Nuget.

**Comment by JudahGabriel** [comment]
Yep, thanks! I [submitted a PR for this](this: https://github.com/migrating-ravens/RavenMigrations/pull/44) - it upgrades this project to use .NET Core 2.1 and Raven 4.
