### ISSUE TITLE
Migration version changed from int64 to int32

### ISSUE THREAD

**Issue by espenrl** [migrating-ravens/RavenMigrations#49]
![image](https://user-images.githubusercontent.com/4621581/50645406-c6a70100-0f73-11e9-9598-0915bbc778a4.png)

We have taken a dependency on using version numbers above the int32 range. This is now hindering us upgrading from v2 to v4. Is it possible to change it back to int64?

**Comment by JudahGabriel** [comment]
Yeah, alright, we can change that. I'll do that today.

**Comment by JudahGabriel** [comment]
Fixed. I've updated the source and published a new NuGet package with the update.

**Comment by espenrl** [comment]
That was fast. Thank you!

**Comment by espenrl** [comment]
Just tested it and it works fine. `MigrationOptions.ToVersion` is still int32 though.

**Comment by JudahGabriel** [comment]
Ah, that's what I get for "fixing" it so fast. :-) Try now? Nuget package 4.1.4 should have the fix, including ToVersion supporting longs.
