### ISSUE TITLE
Consider preventing migrations from running simultaneously from multiple web apps

### ISSUE THREAD

**Issue by JudahGabriel** [migrating-ravens/RavenMigrations#50]
As described in Andrew Locke's post on why [running migrations on startup is a bad idea](https://andrewlock.net/running-async-tasks-on-app-startup-in-asp-net-core-part-3-feedback/), his objection boils down to having multiple apps running simultaneously. One app starts running migrations, the next app starts running migrations, and now we've got trouble.

We may want to use Raven's CompareXChange to enter a migrations cluster-wide "lock", so that no other migrations can be run from other app instances.

**Comment by SbiCA** [comment]
@JudahGabriel I agree that this should be a feature, I guess a simple solution could be to use a `lock` document since that's the common resource amongst the app instances and using `session.Load<MigrationLock>("THE LOCK ID") == null ? "Good To Go" : "Wait or cancel" ` . Or at least provide a hook e.g. virtual method in `MigrationRunner` to allow overriding the run behaviour.

**Comment by SbiCA** [comment]
I created a small sample how this could look like let me know if I should create a PR [sample code](https://github.com/SbiCA/raven-migrations-single-instance/blob/master/Program.cs#L30)

**Comment by JudahGabriel** [comment]
That will work in a single node, but isn't reliable in a cluster.

Instead of a lock document, you should instead use [Raven compare/exchange](https://ravendb.net/docs/article-page/4.2/csharp/client-api/operations/compare-exchange/overview), which works in a cluster.

**Comment by JudahGabriel** [comment]
If you can update your sample to use compare/exchange, I'd be glad to accept that as a PR.

**Comment by SbiCA** [comment]
@JudahGabriel  totally I agree I update the sample to use CompareExchange it much simpler 😄 I think it could have also worked with the lock document if when using [Write assurance and database groups](https://ravendb.net/docs/article-page/4.0/csharp/client-api/cluster/how-client-integrates-with-replication-and-cluster#write-assurance-and-database-groups) but I prefer the Exchange approach.

**Comment by JudahGabriel** [comment]
Great. I'd gladly accept a PR with those changes.

**Comment by SbiCA** [comment]
I'll try to do create the PR this week

**Comment by JudahGabriel** [comment]
I've released RavenMigrations 4.3, which prevents simultaneous migrations by default. 😎
