### ISSUE TITLE
OpenSession without specifiying Database

### ISSUE THREAD

**Issue by espenrl** [migrating-ravens/RavenMigrations#53]
Hi,

Maybe I'm wrong, but shouldn't this line specify the database parameter as is done elsewhere?

https://github.com/migrating-ravens/RavenMigrations/blob/3e812f8c5d513ef640bce450126fd92c5d76f3d8/Raven.Migrations/Migration.cs#L112

Other places:

https://github.com/migrating-ravens/RavenMigrations/blob/3e812f8c5d513ef640bce450126fd92c5d76f3d8/Raven.Migrations/Migration.cs#L57

https://github.com/migrating-ravens/RavenMigrations/blob/3e812f8c5d513ef640bce450126fd92c5d76f3d8/Raven.Migrations/Migration.cs#L81

**Comment by JudahGabriel** [comment]
Thanks! I've fixed this in the code. It'll be included in the next release. Let me know if you need this sooner.
