### ISSUE TITLE
Latest version 5.0.0 on NuGet is incompatible with full framework

### ISSUE THREAD

**Issue by lahma** [migrating-ravens/RavenMigrations#54]
I couldn't find the source that corresponds the published package here, but it seems that the target has been changed from netstandard2.0 to netstandard2.1. netstandard2.1 only works with .NET Core 3.1 and thus makes this package unusable from full framework which can only handle netstandard2.0.

Could the target be changed back to nestandard2.0?

**Comment by JudahGabriel** [comment]
For now, I'd recommend using the previous stable version.

**Comment by lahma** [comment]
Is there a long term plan for versions?

**Comment by JudahGabriel** [comment]
Well, I had assumed most folks using this library are on .NET Core, as that is where all new development is taking place.

What's the story for .NET Standard and the .NET framework? Will there be a .NET framework that implements .NET Standard 2.1?

**Comment by lahma** [comment]
Unfortunately no. Netstandard2.0 is presumably last version full framework will ever support, from 4.6.1 onward I guess.

**Comment by JudahGabriel** [comment]
I think it's unsustainable for us, then, to continue supporting that old version of .NET Standard. I think your best bet going forward is:

- Use the previous stable RavenMigrations
- If you anticipate active development in your project, look at migrating to .NET Core

**Comment by lahma** [comment]
Fair enough. I think my original expectations came from RavenDB.Client supporting .NETStandard2.0, but naturally you call the shots 🙂
