### ISSUE TITLE
Release 5.0.1

### ISSUE THREAD

**Issue by lahma** [migrating-ravens/RavenMigrations#59]
Would it be possible to release current master as 5.0.1 to NuGet, it would clean up the dependencies and add support supplying the database name to operations. We've been running our custom build for a while and it's basically same as your current master 🙂

**Comment by JudahGabriel** [comment]
Sure thing! Done. It should show up on NuGet within the hour.

**Comment by lahma** [comment]
Thank you so much! 👍🏻
