### ISSUE TITLE
Project little works then stops working

### ISSUE THREAD

**Issue by radenkozec** [migrating-ravens/RavenMigrations#60]
I was able to get 2-3 migrations to run.
Later all stop working and no able to get it run even all migrations have migration attributes and inherit from migration.

Do you use some kind of local cache?

**Comment by radenkozec** [comment]
After I have created options.PreventSimultaneousMigrations = false; all works normally.

**Comment by JudahGabriel** [comment]
Did you run a migration in the debugger and kill the app before migrations could finish?

Raven.Migrations has a feature that prevents simultaneous migrations from running concurrently. (e.g. if you have 2 instances of your app running, you don't want both to run migrations.)

To accomplish this, Raven.Migration sets a cluster-wide compare/exchange value to ensure no other instances are running. This compare/exchange value has an expiration time, so if you just wait, things will work. But if you need to clear out the compare exchange value manually, just go into Raven Studio -> Documents -> Compare/Exchange. You'll see a Raven.Migrations value there. Delete it and you'll be able to run migrations.

![image](https://user-images.githubusercontent.com/312936/159331422-3b16ca6d-0d0b-4a3d-9157-e9b50909b7ad.png)
