### ISSUE TITLE
PatchCollection has old signature in latest nuget package

### ISSUE THREAD

**Issue by danielwinkler** [migrating-ravens/RavenMigrations#65]
I am using the latest RavenMigrations package
https://www.nuget.org/packages/RavenMigrations/5.0.1

It happened after
https://github.com/migrating-ravens/RavenMigrations/commit/8f84f7aff181c7c776b361a9980e24e9d43b91ea

which changed the signature of `PatchCollection`

```
protected Operation PatchCollection(string rql, bool waitForCompletion = true)
```
to
```
protected Operation PatchCollection(string rql, bool waitForCompletion = true, TimeSpan? staleTimeout = null)
```

Is it possible to create another release that has this change?

**Comment by JudahGabriel** [comment]
Sure thing. I'll publish today and let you know when it's up.

**Comment by danielwinkler** [comment]
Thanks so much for reacting that quickly!
