### ISSUE TITLE
Grant me admin access to this repo?

### ISSUE THREAD

**Issue by JudahGabriel** [migrating-ravens/RavenMigrations#66]
Hey @khalidabuhakmeh or @dportzline83 - do either of you have admin access to this repo? If so, can you grant me admin access?

I was going to add a Github secret to setup automatic Nuget publishing for the Nuget package for this repo, only to realize I don't have admin access, and thus, I can't add Github secrets. (In fact, the whole Settings tab in Github is unavailable to me for this repo.)

If you have admin access, can you grant me access?

**Comment by khalidabuhakmeh** [comment]
Hi folks, I've granted both of you admin access. Cheers :)
